version: '2'
services:
    loopback:
        build: loopback/.
        command: node .
        #depends_on: 
        volumes:
            - ./loopback/server/:/loopback/server/
            - ./loopback/client/:/loopback/client/
            - /loopback/node_modules
        restart: always
        #ports:
        #    - "3000:3000"
        networks:
            - nginx_default

    #ror:
    #    build: ror/.
    #    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 80 -b '0.0.0.0'" 
    #    volumes:
    #        - ./ror/:/ror
        #ports:
        #    - "3000:3000"
    #    restart: always
    #    networks:
    #        - nginx_default
    node:
        build: node/.
        command: node server2.js
        #depends_on: 
        depends_on:
            - loopback
        volumes:
            - ./node/:/node
            - /node/node_modules
        restart: always
        networks:
            - nginx_default
    http:
        build: http/.
        command: http-server . -p 80
        depends_on: 
            - loopback
        #ports:
        #    - "8001:80"
        volumes:
            - ./http/:/http
            - /http/node_modules
        restart: always
        networks:
            - nginx_default
    reactjs:
        build: reactjs/.
        command: http-server ./build/. -p 80
        depends_on: 
            - loopback
        #ports:
        #    - "8001:80"
        volumes:
            - ./reactjs/:/reactjs
            - /reactjs/node_modules
        restart: always
        networks:
            - nginx_default
    ionic:
        build: ionic/.
        #command: bash -c "npm rebuild node-sass --force && ionic serve --no-interactive --address 0.0.0.0"
        command: http-server ./platforms/browser/www -p 80
        #command: bash -c "ionic cordova run browser --no-interactive --address 0.0.0.0 --nolivereload"
        #depends_on: 
        #    - ror
        #ports:
        #    - "8080:80"
        volumes:
            - ./ionic/:/ionic
        restart: always
        networks:
            - nginx_default

    # redis:
    #    build: redis/.
    #    command: bash -c "sysctl vm.overcommit_memory=1 && redis-server /usr/local/etc/redis/redis.conf"

        #image: redis
        #ports:
        #    - "6379:6379"
        #   volumes:
        #    - /redis/redis.conf:/usr/local/etc/redis/redis.conf
        #restart: always
        #networks:
        #    - nginx_default
networks:
    nginx_default:
        external: true
