version: '2'
services:
    node:
        build: node/.
        command: node server2.js
        #depends_on: 
        #depends_on:
        #    - loopback
        mem_limit: 64m
        volumes:
            - ./node/:/node
            - /node/node_modules
        #restart: always
        networks:
            - nginx_default
    reactjs:
        build: reactjs/.
        command: serve -s ./build/. -p 80
        #depends_on: 
        #    - loopback
        #ports:
        #    - "8001:80"
        restart: always
        volumes:
            - ./reactjs/:/reactjs
            - /reactjs/node_modules
        mem_limit: 64m
        networks:
            - nginx_default
networks:
    nginx_default:
        external: true
