version: '2'
services:
    ror:
        build: ror/.
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes:
            - ./ror/db:/apollo/db
        #    - ./ror/app:/apollo/app
        ports:
            - "3000:3000"
    node:
        build: node/.
        command: node server.js
        #depends_on: 
        links:
            - ror
            - redis
        volumes:
            - ./node/server.js:/apollo/server.js
            - ./node/common.js:/apollo/common.js
    http:
        build: http/.
        command: http-server . -p 80
        depends_on: 
            - ror
        ports:
            - "8001:80"
        volumes:
            - ./http/js:/apollo/js
            - ./http/css:/apollo/css
            - ./http/partials:/apollo/partials
            - ./http/favicon.ico:/apollo/favicon.ico
            - ./http/index.html:/apollo/index.html
    redis:
        image: redis
        ports:
            - "6379:6379"
