apiVersion: apps/v1
kind: Deployment
metadata:
  name: apollo-reactjs-deployment
  labels:
    app: apollo-reactjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apollo-reactjs
  template:
    metadata:
      labels:
        app: apollo-reactjs
    spec:
      containers:
      - name: apollo-reactjs
        image: stevenluong/apollo-reactjs:v0.2
        #ports:
        #- containerPort: 80
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        effect: "NoSchedule"
        operator: "Exists"
